### ISSUE TITLE
New configuration does not work. 

### ISSUE THREAD

**Issue by tasomaniac** [fourlastor/pickle#40]
I'm not sure if it works in Kotlin Gradle DSL but below does not work with Groovy projects. 

https://github.com/fourlastor/pickle/#configuration

```
pickle {
    androidTest {
      featuresDir = 'features' // location of features inside `androidTest/src/assets`
    }
}
```

The error is: 

```
> Could not find method androidTest() for arguments [setup_bdd_test_8aihs9lwmlmtcmk67w5u4oihx$_run_closure1$_closure4@6b3ad53c] on object of type com.fourlastor.pickle.PicklePlugin$Extension.
```

**Comment by fourlastor** [comment]
You're right, I think it should be `androidTest = `

**Comment by tasomaniac** [comment]
It's a common practice to support the usage described in the README though. It works out of the box if you use Gradle's property and input APIs.

Otherwise the way to do it is to have

```
fun androidTest(action: Action<TestExtension>) {
    action.apply(...)
}
```
